-- migrations/014_notification_preferences.sql

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS notif_lembretes BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS notif_alertas_risco BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS notif_insights BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS notif_gamificacao BOOLEAN NOT NULL DEFAULT TRUE;
